music-app/config/routes.rb
Rails.application.routes.draw do
  get 'albums/new'

  get 'albums/show'

  get 'albums/edit'

  get 'bands/new'

  get 'bands/edit'

  get 'bands/index'

  get 'bands/show'

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

music-app/app/models/album.rb
class Album < ActiveRecord::Base
  PERFORMANCE = %w(live studio)

  validates :performance, :band_id, :title, presence: true
  validates :performance, inclusion: { in: PERFORMANCE }

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

music-app/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
end

music-app/app/models/track.rb
class Track < ActiveRecord::Base
  SPECIAL = %w(bonus, regular)

  belongs_to :album

  validates :album_id, :title, :special, presence: true
  validates :special, inclusion: { in: SPECIAL }
end

music-app/app/models/user.rb
class User < ActiveRecord::Base
  validates :email,
            :session_token,
            presence: true,
            uniqueness: true

  validates :password, presence: true, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by_email(email)

    return nil if @user.nil?
    @user.is_password?(password) ? @user : nil
  end


  private

    def ensure_session_token
      self.session_token ||= self.class.generate_session_token
    end

end

music-app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
  end

  def show
  end

  def edit
  end
end

music-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out_user!
    @current_user = nil
    session[:session_token] = nil
  end
end

music-app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
  end

  def edit
    @band = Band.find(params[:id])
  end

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find_by(id: params[:id])
    unless @band
      flash[:errors] = "Band with id #{params[:id]} does not exit"
      redirect_to bands_url
    end
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = "You have successfully created a new band!"
      redirect_to bands_url(@band)
    else
      flash[:error] = @band.errors.full_messages
      redirect_to new_bands_url
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end


  private
    def band_params
      params.require(:band).permit(:name)
    end
end

music-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:email],
                                     params[:password])
    if @user
      log_in_user!(@user)
      flash[:success] = "Welcome back to the music-app"
      redirect_to user_url(@user)
    else
      flash[:error] = "Invalid username/password"
      redirect_to new_session_url
    end
  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end
end

music-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      flash[:success] = "Welcome to the music-app!"
      redirect_to user_url(@user)
    else
      flash.now[:error] = "Invalid username/password"
      render :new
    end
  end

  private
    def user_params
      params.require(:users).permit(:email, :password)
    end
end

music-app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music-app/app/helpers/application_helper.rb
module ApplicationHelper
end

music-app/app/helpers/bands_helper.rb
module BandsHelper
end

music-app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music-app/app/helpers/users_helper.rb
module UsersHelper
end

music-app/app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

music-app/app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

music-app/app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

music-app/app/views/bands/_band.html.erb
<ul>
  <li>Name: <%= link_to band.name, band_url(band) %>
  <%= link_to "delete", band_url(band), method: :delete %></li>
</ul>

music-app/app/views/bands/edit.html.erb
<h1>Bands#edit</h1>
<p>Find me in app/views/bands/edit.html.erb</p>

music-app/app/views/bands/index.html.erb
<h1>Bands</h1>
<%= render @bands %>

music-app/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'shared/band_form', action: bands_url, method_type: "POST" %>

music-app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

music-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/errors' %>
<%= render 'shared/header' %>
<%= yield %>

</body>
</html>

music-app/app/views/shared/_band_form.html.erb
<form action="<%= action %>" method="POST">
<input type="hidden" name="_method" method="<%= method_type %>">
<input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

<label for="band_name">Name</label>
<input type="text"
        name="band[name]"
        id="band_name"
        value="<%= @band.name %>">
<br>

<input type="submit">
</form>

music-app/app/views/shared/_errors.html.erb
<% flash.each do |type, msg| %>
  <%= "#{type}: #{msg}" %>
<% end %>

music-app/app/views/shared/_form.html.erb
<form action="<%= action %>" method="post">
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

<label for="user_email">Email</label>
<input
  type="text"
  name="users[email]"
  id="user_email"
  value="<%= @user.email %>">
<br>

<label for="user_password">Password</label>
<input
  type="password"
  name="users[password]"
  id="user_password">
<br>

<input type="submit">
</form>

music-app/app/views/shared/_header.html.erb
<ul>
  <% if logged_in? %>
    <li><%= link_to "Log out", session_url, method: :delete %></li>
  <% else %>
    <li><%= link_to "Log in", new_session_url %></li>
  <% end %>
</ul>

music-app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'shared/form', action: users_url %>

music-app/app/views/users/show.html.erb
<h1><%= @user.email %></h1>